; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
boards_dir = boards
lib_dir = lib
src_dir = src
include_dir = include
build_dir = build

[env:LVGL_8-4-0]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = JC3248W535EN
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
lib_deps =
	lvgl/lvgl@8.4.0
build_flags =
	-D LV_CONF_PATH="${PROJECT_DIR}/include/lv_conf_8.4.0.h"